# Merging RAS and NFL Draft Dataset

In [32]:
import pandas as pd
import string
import re

In [25]:
df_draft = pd.read_csv("../data/nfl_draft_data.csv", delimiter=";")
df_ras = pd.read_csv("../data/RAS_1987_present.csv")

In [9]:
print(len(df_draft))
df_draft.head(2)

14163

,year,name,college,pos,height,weight,hand_size,arm_length,wonderlic,40_yard,...,college_pass_int,college_pass_cmp_pct,college_rush_yds,college_rush_td,college_rec_yds,college_rec_td,college_tackles,college_sacks,college_ints,college_fumbles
0,1987,Mike Adams,Arizona State,CB,69.8,198.0,8.50,30.5,NaN,4.42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1987,John Adickes,Baylor,C,74.8,266.0,10.25,30.0,NaN,4.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print(len(df_ras))
df_ras.head(2)

9751

,Link,Name,POS,College,Year,RAS,Alltime RAS,Round,Draft Team
0,"<a class=""nt_btn "" style=""color: rgba(0, 0, 0,...",Justin Fargas,RB,Southern California,2003,10.0,10.0,3,Raiders
1,"<a class=""nt_btn "" style=""color: rgba(0, 0, 0,...",David Buehler,PK,Southern California,2009,10.0,10.0,5,Cowboys

### Looking at problem player names

In [16]:
print(df_ras[df_ras['Name'] == 'A.J. Brown'])
print("")
print(df_draft[df_draft['name'] == 'A.J. Brown'])

                                                   Link        Name POS  \
1945  <a class="nt_btn " style="color: rgba(0, 0, 0,...  A.J. Brown  WR

          College  Year   RAS  Alltime RAS  Round Draft Team
1945  Mississippi  2019  8.59         8.89      2     Titans

       year        name      college pos  height  weight  hand_size  \
11887  2019  A.J. Brown  Mississippi  WR    72.5   226.0       9.75

       arm_length  wonderlic  40_yard  ...  college_pass_int  \
11887       32.88        NaN     4.49  ...               NaN

       college_pass_cmp_pct  college_rush_yds  college_rush_td  \
11887                   NaN               0.0              0.0

       college_rec_yds  college_rec_td college_tackles college_sacks  \
11887           2984.0            19.0             NaN           NaN

       college_ints college_fumbles
11887           NaN             NaN

[1 rows x 59 columns]

### Make Name, Team, Round merge compliant

In [19]:
print(df_ras.dtypes)
print("")
print(df_draft.dtypes)

Link               str
Name               str
POS                str
College            str
Year             int64
RAS            float64
Alltime RAS    float64
Round            int64
Draft Team         str
dtype: object

year                          int64
name                            str
college                         str
pos                             str
height                      float64
weight                      float64
hand_size                   float64
arm_length                  float64
wonderlic                   float64
40_yard                     float64
bench_press                 float64
vert_leap                   float64
broad_jump                  float64
shuttle                     float64
3_cone                      float64
60yd_shuttle                float64
simple_pos                      str
tag                             str
drafted                        bool
player_id                       str
draft_round                 float64
draft_pick                  float64
team                            str
year_max                    float64
age                         float64
all_pros_first_team         float64
pro_bowls                   float64
years_as_primary_starter    float64
career_av                   float64
g                           float64
pass_cmp                    float64
pass_att                    float64
pass_yds                    float64
pass_td                     float64
pass_int                    float64
rush_att                    float64
rush_yds                    float64
rush_td                     float64
rec                         float64
rec_yds                     float64
tackles_solo                float64
rec_td                      float64
def_int                     float64
sacks                       float64
college_id                      str
college_link                    str
college_games               float64
college_pass_yds            float64
college_pass_td             float64
college_pass_int            float64
college_pass_cmp_pct        float64
college_rush_yds            float64
college_rush_td             float64
college_rec_yds             float64
college_rec_td              float64
college_tackles             float64
college_sacks               float64
college_ints                float64
college_fumbles             float64
dtype: object

## Start with RAS Dataset 
### [Name]
### We want to make name 
<li>all lowercase</li>
<li>trim whitespace</li>
<li>contain just letters, no punctuation</li>

In [37]:
regex_pattern = f"[{re.escape(string.punctuation) + string.whitespace}]"

In [45]:
df_ras['name_for_merge'] = df_ras['Name'].str.lower().str.strip().str.replace(regex_pattern, "", regex=True)

# print(df_ras[df_ras['name_for_merge'] == 'ajbrown'])
print(df_ras[df_ras['name_for_merge'] == 'pauloconnor'])
# df_ras.head()

                                                   Link           Name POS  \
7300  <a class="nt_btn " style="color: rgba(0, 0, 0,...  Paul O'Connor  OG

     College  Year   RAS  Alltime RAS  Round Draft Team name_for_merge
7300   Miami  1987  2.31         1.85      5     Giants    pauloconnor

### [Drafting Team]

In [46]:
df_ras['Draft Team'] = df_ras['Draft Team'].str.lower()

In [49]:
df_ras['Draft Team'].unique()

<StringArray>
[   'raiders',    'cowboys',      'colts',     'giants',       'jets',
 'commanders',      'bills', 'buccaneers',     'eagles',    'bengals',
   'seahawks',   'panthers',    'packers',    'jaguars',      '49ers',
      'lions',     'chiefs',    'vikings',     'texans',     'titans',
     'browns',   'dolphins',    'falcons',      'bears',     'saints',
   'chargers',  'cardinals',   'steelers',    'broncos',   'patriots',
     'ravens',       'rams']
Length: 32, dtype: str

In [50]:
df_ras.head()

,Link,Name,POS,College,Year,RAS,Alltime RAS,Round,Draft Team,name_for_merge
0,"<a class=""nt_btn "" style=""color: rgba(0, 0, 0,...",Justin Fargas,RB,Southern California,2003,10.0,10.0,3,raiders,justinfargas
1,"<a class=""nt_btn "" style=""color: rgba(0, 0, 0,...",David Buehler,PK,Southern California,2009,10.0,10.0,5,cowboys,davidbuehler
2,"<a class=""nt_btn "" style=""color: rgba(0, 0, 0,...",Anthony Richardson,QB,Florida,2023,10.0,10.0,1,colts,anthonyrichardson
3,"<a class=""nt_btn "" style=""color: rgba(0, 0, 0,...",Lorenzo Carter,LB,Georgia,2018,10.0,10.0,3,giants,lorenzocarter
4,"<a class=""nt_btn "" style=""color: rgba(0, 0, 0,...",Zack Kuntz,TE,Old Dominion,2023,10.0,10.0,7,jets,zackkuntz

## NFL Draft Dataset

### Formatting

<li>Name</li>
<li>Team</li>
<li>Round</li>

### Start with Name
### Apply same formatting as the RAS dataset

In [53]:
df_draft['name_for_merge'] = df_draft['name'].str.lower().str.strip().str.replace(regex_pattern, "", regex=True)

#print(df_ras[df_ras['name_for_merge'] == 'ajbrown'])
# print(df_draft[df_draft['name_for_merge'] == 'pauloconnor'])
df_draft.head()

,year,name,college,pos,height,weight,hand_size,arm_length,wonderlic,40_yard,...,college_pass_cmp_pct,college_rush_yds,college_rush_td,college_rec_yds,college_rec_td,college_tackles,college_sacks,college_ints,college_fumbles,name_for_merge
0,1987,Mike Adams,Arizona State,CB,69.8,198.0,8.50,30.50,NaN,4.42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mikeadams
1,1987,John Adickes,Baylor,C,74.8,266.0,10.25,30.00,NaN,4.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,johnadickes
2,1987,Tommy Agee,Auburn,FB,71.8,217.0,9.00,30.75,NaN,NaN,...,NaN,1733.0,10.0,321.0,3.0,NaN,NaN,NaN,NaN,tommyagee
3,1987,David Alexander,Tulsa (OK),C,75.0,279.0,10.50,32.75,NaN,5.13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,davidalexander
4,1987,Lyneal Alston,Southern Mississippi,WR,72.1,202.0,10.00,33.00,NaN,4.64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lynealalston

In [56]:
df_draft['team'].unique()

<StringArray>
[                       nan,            'Chicago Bears',
         'Seattle Seahawks',      'Philadelphia Eagles',
      'St. Louis Cardinals',            'New York Jets',
     'Tampa Bay Buccaneers',     'New England Patriots',
       'New Orleans Saints',          'New York Giants',
            'Detroit Lions',           'Houston Oilers',
       'Indianapolis Colts',      'San Francisco 49ers',
       'Cincinnati Bengals',       'San Diego Chargers',
        'Minnesota Vikings',      'Los Angeles Raiders',
         'Los Angeles Rams',           'Miami Dolphins',
         'Cleveland Browns',            'Buffalo Bills',
      'Pittsburgh Steelers',        'Green Bay Packers',
      'Washington Redskins',          'Atlanta Falcons',
           'Dallas Cowboys',       'Kansas City Chiefs',
           'Denver Broncos',        'Phoenix Cardinals',
        'Arizona Cardinals',          'Oakland Raiders',
     'Jacksonville Jaguars',        'Carolina Panthers',
           'St. Louis Rams',         'Baltimore Ravens',
         'Tennessee Oilers',         'Tennessee Titans',
           'Houston Texans',     'Los Angeles Chargers',
        'Las Vegas Raiders', 'Washington Football Team',
    'Washington Commanders']
Length: 43, dtype: str